[build]
src = "source"
out = "target"
obj = "target/build"

[io_win]
lib = "io"
lang = "c"
platform = "Windows"

[io_linux]
lib = "io"
lang = "c"
platform = "Linux"

[io_mac]
lib = "io"
lang = "c"
platform = "mac"

# [io_other]
# lib = "io"
# lang = "c"
# platform = "(some other inexistent platform)"
