[build]
src = "source"
out = "target"
obj = "target/build"
cc = "msvc"

[build.c]
std = "c11"

[build.cpp]
std = "c++20"

[hello]
lib = "hello"

[main]
exe = "main"
libs = [
  "hello"
]
link = [
  "/SUBSYSTEM:CONSOLE"
]

[main.c]
std = "c17"
