[build]
src = "source"
out = "target"
obj = "target/build"
bip = "3.0+"

[build.c]
define = {SOMETHING = 1}

[hello]
lib = "hello"
lang = "c"

[hello.c]
compiler = "msc"

[main]
exe = "main"
lang = "c"
libs = [
  "hello"
]
link = [
  "/SUBSYSTEM:CONSOLE"
]

[main.c]
define = {MAIN_BUILD = 1}

[main.cpp]
define = {MAIN_BUILD = 1}
